sudo: required
notifications:
email: false
language: java
jdk:
- openjdk7
install:
- sudo add-apt-repository ppa:dns/gnu -y
- sudo apt-get update -qq
- sudo apt-get install -y autoconf dos2unix icoutils python-requests
script:
- tools/build-appimagekit.sh
- tools/build-decodeir.sh
- tools/build-exchangeir.sh
- tools/build-jcommander.sh
- tools/build-minimal-json.sh
- tools/build-java-readline.sh
- tools/build-tonto.sh -n
- mvn install -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
- tools/travis2github.py IrScrutinizer/target/IrScrutinizer-bin.zip IrScrutinizer/target/IrScrutinizer-*-app.zip IrScrutinizer/target/IrScrutinizer-*AppImage
